
import React, { useState } from 'react';
import { Download, X, FileText } from 'lucide-react';
import { ScheduleItem, Project } from '../services/storageService';

interface SceneCallSheetProps {
  project: Project;
  allScenes: ScheduleItem[];
  onClose: () => void;
}

const SceneCallSheet: React.FC<SceneCallSheetProps> = ({
  project,
  allScenes,
  onClose
}) => {
  const generateProjectCallSheet = () => {
    const callSheetData = {
      project: project.title,
      scenes: allScenes.map(scene => ({
        scene: scene.scene,
        description: scene.notes || 'No description available'
      }))
    };

    return callSheetData;
  };

  const downloadProjectCallSheet = () => {
    const callSheet = generateProjectCallSheet();
    const content = `
PROJECT CALL SHEET

Project: ${callSheet.project}

SCENES:
${callSheet.scenes.map(scene => `
SCENE: ${scene.scene}
DESCRIPTION: ${scene.description}
---`).join('')}

Generated by Movie Production Management System
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `project-call-sheet-${callSheet.project.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    alert('Project call sheet downloaded successfully!');
  };

  const callSheetData = generateProjectCallSheet();

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h3 className="text-xl font-semibold text-gray-900">Project Call Sheet - All Scenes</h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          {/* Project Information */}
          <div className="bg-gray-50 rounded-lg p-4">
            <h4 className="font-medium text-gray-900 mb-3">Project Information</h4>
            <div className="space-y-2">
              <div className="flex items-center space-x-2">
                <FileText className="h-4 w-4 text-gray-400" />
                <span className="font-medium">{callSheetData.project}</span>
              </div>
              <p className="text-sm text-gray-600">Total Scenes: {callSheetData.scenes.length}</p>
            </div>
          </div>

          {/* All Scenes */}
          <div>
            <h4 className="font-medium text-gray-900 mb-4">All Scenes</h4>
            <div className="space-y-4 max-h-96 overflow-y-auto">
              {callSheetData.scenes.map((scene, index) => (
                <div key={index} className="bg-white border border-gray-200 rounded-lg p-4">
                  <div className="font-medium text-gray-900 mb-2">{scene.scene}</div>
                  <div className="text-gray-700 text-sm whitespace-pre-wrap">
                    {scene.description}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Preview */}
          <div>
            <h4 className="font-medium text-gray-900 mb-3">Preview</h4>
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm font-mono whitespace-pre-wrap max-h-64 overflow-y-auto">
              {`PROJECT CALL SHEET

Project: ${callSheetData.project}

SCENES:
${callSheetData.scenes.map(scene => `
SCENE: ${scene.scene}
DESCRIPTION: ${scene.description}
---`).join('')}

Generated by Movie Production Management System`}
            </div>
          </div>

          {/* Actions */}
          <div className="flex justify-end">
            <button
              onClick={downloadProjectCallSheet}
              className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              <Download className="h-4 w-4" />
              <span>Download Project Call Sheet</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SceneCallSheet;
